[build]
  base = "."
  publish = "dist"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 确保构建在正确的目录中运行
[build.processing]
  skip_processing = false 